modified:   bin/anything2mp3

diff --git a/bin/anything2mp3 b/bin/anything2mp3
--- a/bin/anything2mp3
+++ b/bin/anything2mp3
@@ -24,30 +24,36 @@
 
 # note: Using parallel (apt-get install parallel) will give enormous encoding speed boost. 
 
-command -v lame >/dev/null 2>&1 || { echo >&2 "I require lame but it's not installed, exiting."; exit 1; }
 command -v mediainfo >/dev/null 2>&1 || { echo "I need mediainfo installed." ; exit 1; }
-command -v ffmpeg_static >/dev/null 2>&1 || { echo "I need ffmpeg_static on the path." ; exit 1; }
+ffmpeg_static -hide_banner -codecs 2>&1 | grep lame >/dev/null 2>&1 || { echo "I need ffmpeg_static on the path and it has to have lame mp3 encoder." ; exit 1; }
+
+# functions
+encode() { # put your encoding settings here
+    
+                ffmpeg_static -hide_banner -loglevel quiet -i "$expanded" -vn -y -codec:a libmp3lame -q:a 3 "$dir/$base.mp3" 
+}
 
 # http://wiki.hydrogenaud.io/index.php?title=Lame#Very_high_quality:_HiFi.2C_home.2C_or_quiet_listening.2C_with_best_file_size
 # Very high quality: HiFi, home, or quiet listening, with best file size
 # -V0 (~245 kbps), -V1 (~225 kbps), -V2 (~190 kbps) or -V3 (~175 kbps) are recommended.
-# These VBR settings will normally produce transparent results. Audible differences between these presets may exist, but are rare. 
+# These VBR settings will normally produce transparent results. Audible differences between these presets may exist, but are rare.
 
-encode() { # put your encoding settings here
-    
-    # encode 
-    ffmpeg_static -i "$expanded" -vn -y -f wav - 2> /dev/null| lame -V3 - "$dir/$base.tmp.mp3" # fixme: this tmp file would probably better sit in some tmp folder
-    # copy metadata
-    ffmpeg_static -i "$dir/$base.tmp.mp3" -i "$expanded" -y -map_metadata 1:g -vn -acodec copy "$dir/$base.mp3"
-    rm "$dir/$base.tmp.mp3"
-
+absdiff() { 
+                echo -n "$(( (a<b) ? b-a : a-b ))" 
 }
+# end functions
+
 
 while [ $# -gt 0 ]; do
 
+	# temp dir http://mywiki.wooledge.org/BashFAQ/062
+   	temp_dir=/tmp/$RANDOM-$$
+   	trap '[ -n "$temp_dir" ] && rm -fr "$temp_dir"' EXIT
+   	mkdir -m 700 "$temp_dir" || { echo '!! unable to create a tempdir' >&2; temp_dir=; exit 1; } # end temp dir
+
   
     expanded=$(readlink -f "$1")
-    echo ".............................."
+    # echo ".............................."
     echo "$expanded"
     
     base=$(basename "${1}")     # basename, like                file.flac
@@ -58,15 +64,32 @@ while [ $# -gt 0 ]; do
         # Do some checks first
         if [ -f "$dir/$base.mp3" ]
         then # mp3 file in existance, do some duration checking
-            echo "the file exists, checking if source and mp3 durations match"
+            echo "    the file exists, checking if source and mp3 durations match"
         
-                if diff <(mediainfo "$expanded" | grep -m 1 Duration) <(mediainfo "$dir/$base.mp3" | grep -m 1 Duration)
+                # mediainfo "--Inform=General;%Duration%"
+                
+                a=$(mediainfo "--Inform=General;%Duration%" "$expanded")
+                b=$(mediainfo "--Inform=General;%Duration%" "$dir/$base.mp3")
+                
+                if diff <(echo "$a") <(echo "$b") >/dev/null 2>&1
+       
                 then
-                    echo "yes, durations match, skipping"
+                    echo "    yes, durations match exactly, skipping" # This will probably never happen
                 else
-                    echo "no, durations does not match, reencoding" 
-                    encode 
-                   
+                    echo "    no, durations does not match exactly" 
+                    
+                    # echo "$a" "$b"
+                    echo -n "    "
+                    absdiff "$a" "$b"
+                    echo -n "ms difference"
+                        # this 200 is just some value in miliseconds = max difference allowed,
+                        # if samplerate is 48 kHz, then it equals to 200x48=9600 samples
+                        if (( $(absdiff "$a" "$b") < 200 )) 
+                        then
+                            echo " < but close enough (200 ms is max allowed)"
+                        else
+                            encode
+                        fi
                 fi
             
             
@@ -74,5 +97,11 @@ while [ $# -gt 0 ]; do
             encode
         fi
    
+   
+       [ -n "$temp_dir" ] && rm -fr "$temp_dir" # deleting temp dir
+   
     shift
+    
+
+    
 done
